CREATE SEQUENCE felhasznalo_seq
START WITH 100
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE esemeny_seq
START WITH 1000
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE esemeny_kedveles_seq
START WITH 2000
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE esemeny_regisztracio_seq
START WITH 3000
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE helyszin_seq
START WITH 4000
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE kedvelt_kategoriak_seq
START WITH 5000
INCREMENT BY 1
NOCACHE;
